# Copyright 2023–2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CLI utility for running inference on a single/multi stream(s)."""

import os
from typing import Sequence, Any
import numpy as np
import jax
import jax.numpy as jnp

from absl import app

from maxtext.configs import pyconfig
from maxtext.common import profiler
from maxtext.common.gcloud_stub import jetstream, is_decoupled
from maxtext.inference.maxengine import maxengine
from maxtext.multimodal import processor as mm_processor
from maxtext.multimodal import utils as mm_utils
from maxtext.utils import max_utils

_config_lib, engine_api, _token_utils, _tokenizer_api, _token_params_ns = jetstream()
# Placeholder: internal

# Number of text sequences to process in a single batch.
# A batch is hardware limit (total slots), while _NUM_STREAMS is a counter of
# how many slots are currently used.
# It is 1 because decode.py is used to test and debug a single prompt.
_NUM_STREAMS = 1


def _batch_first_result_token(first_tokens: list[Any], batch_size: int):
  """Batches together a list of first result tokens from prefill calls.

  This is needed because prefill currently returns the first token as a batch of size 1
  to optimize latency to first token without padding to the configured batch size, while
  generate returns a batch of configured size. This function batches a list of
  such single-element first tokens into one batch to simulate the normal processing
  that first tokens are generated by generate.

  Args:
    first_tokens: A list of `ResultTokens` representing first token returned by `prefill`
    batch_size: The target batch size to pad to. This should be from the config.
  Return:
    A `ResultTokens` with all first tokens batched as if they are produced by a single
    `generate` step.
  """
  data = jnp.vstack([first_token.data for first_token in first_tokens])

  def _pad_to_batch_size(data: jax.Array, batch_size: int):
    pad_width = [(0, batch_size - data.shape[0]), (0, 0)]
    data = jnp.pad(data, pad_width, mode="constant", constant_values=0)
    return data

  result_tokens = engine_api.ResultTokens(
      data=_pad_to_batch_size(data, batch_size),
      tokens_idx=(0, 1),
      valid_idx=(1, 2),
      length_idx=(2, 3),
      samples_per_slot=1,
  )

  def _all_equals(elements: Sequence[jax.Array], target: jax.Array):
    """Checks if each element equals the given target."""
    stacked = jnp.stack(elements)
    row_comparisons = stacked == target
    return jnp.all(row_comparisons)

  # `tokens_idx`, `valid_idx`, `length_idx` and `samples_per_slot` are hardcoded
  # and should be the same for all first tokens returned from prefill.
  assert _all_equals([jnp.array(t.tokens_idx) for t in first_tokens], jnp.array(result_tokens.tokens_idx))
  assert _all_equals([jnp.array(t.valid_idx) for t in first_tokens], jnp.array(result_tokens.valid_idx))
  assert _all_equals([jnp.array(t.length_idx) for t in first_tokens], jnp.array(result_tokens.length_idx))
  assert _all_equals([jnp.array(t.samples_per_slot) for t in first_tokens], jnp.array(result_tokens.samples_per_slot))

  return result_tokens


def main(argv: Sequence[str]) -> None:
  # Use unsafe (random) hardware bit generator to generate random numbers.
  # This is faster than the default PRNG implementation.
  jax.config.update("jax_default_prng_impl", "unsafe_rbg")
  os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"

  # pyconfig has a hierachy and we can override values using command line flags.
  # The example argv would look like this:
  # [
  #   "src/maxtext/train.py",        # argv[0] is the script name
  #   "base.yml",                   # argv[1] is typically the base config file
  #   "run_name=test_run",          # These are key-value overrides
  #   "per_device_batch_size=4"
  # ]
  config = pyconfig.initialize(argv)
  # Validate the config. Inference doesn't need full state (training/optimizer
  # metadata), it only needs weights. 
  _validate_config(config)
  # config.shardy is a boolean flag (defaulting to True) defined in the MaxText
  #  configuration system (at maxtext/configs/base.yml).
  # It tells MaxText whether to use Shardy, which is JAX's modern "XLA backend"
  # for partitioning code and data across many chips. JAX is currently
  # transitioning from an older system called GSPMD to this newer Shardy system.
  # As noted in the config file, Shardy became the default in JAX starting with
  # version 0.7.0, and GSPMD is expected to be deprecated eventually.
  jax.config.update("jax_use_shardy_partitioner", config.shardy)
  # Diverse Beam Search (DBS) performs "memory swaps" (backtracking) between paths.
  # This makes step-by-step token streaming unreliable as prefixes may change.
  if config.decode_sampling_strategy == "diverse_beam_search":
    max_logging.warning(
        "Diverse Beam Search (DBS) is active. Streaming output is disabled "
        "because beams can backtrack and reorder their cache during generation. "
        "Only the final generated sequence will be accurate."
    )
  # the log goes to absl.logging. It could be console, log stream of a process,
  # or file configured via:
  # python3 decode.py ... --logtostderr=false --log_dir=/path/to/logs
  max_utils.print_system_information()
  # MaxEngine is the high-level coordinator in MaxText that bridges the gap
  # between your raw model code and the high-performance inference environment. 
  # The "Brain" of the inference system. It doesn't just run the model; it
  # manages how the model is laid out across your hardware (TPUs/GPUs), how the
  # memory (KV Cache) is recycled, and how multiple requests are batched
  # together.
  engine = maxengine.MaxEngine(config)
  rng = jax.random.PRNGKey(1234)
  rng, rng_load_params = jax.random.split(rng)
  # Load the weights and distribute them on device mesh. It also manages
  # KV-cache and quantization.
  params = engine.load_params(rng_load_params)
  # Initialize the profiler to trace the model execution.
  # It captures metrics like XLA HLO traces and inter-chip communications.
  prof = profiler.Profiler(config)

  # 3 sources of prompt in priority order:
  # 1. Command line flag --prompt
  # python3 decode.py base.yml prompt="The capital of France is"
  # 2. Custom config file (e.g. llama2-7b.yml)
  # 3. Default in base.yml
  # e.g. prompt: "I love to"
  text = config.prompt
  # Max prompt size. Default is 64 set in base.yml. If more is needed you need
  # to change the config:
  # python3 decode.py ... max_prefill_predict_length=1024
  prefill_length = config.max_prefill_predict_length
  # preprocessor processes video or image input and converts the content to the
  # numbers that the model can understand.
  processor_outputs = mm_utils.PreprocessorOutput()
  if config.use_multimodal:
    # mm_processor processes multi-modal input (image, audio, video) based on
    # different models' demands(Gemma, Lllma, Qwen, etc)
    processor_outputs = mm_processor.preprocess_mm_data(config)
    # get_image_offsets calculates how many tokens all images will turn into.
    # They vary from model to model. This function will calculate it based on
    # the model's spec.
    image_offsets = mm_processor.get_image_offsets(config=config, processor_output=processor_outputs)
    # Subtract the image offsets from the prefill length (token budget).
    prefill_length -= image_offsets
    # Reformat the prompt to include/insert the image placeholders.
    # See MEDIA.md
    text = mm_processor.reformat_prompt(
        prompt=config.prompt,
        image_placeholder=config.image_placeholder,
        video_placeholder=config.video_placeholder,
        model_name=config.model_name,
        num_images=processor_outputs.num_images,
        num_videos=getattr(processor_outputs, 'num_videos', 0),
    )

  # Get the metadata of the tokenizer. e.g.
  # path, token_type (sentencepiece of Llama, T5, huggingface for Mistral or
  # Llama3, tiktoken for OpenAI style like GPT), access_token (for protected
  # models), use_chat_template (for models that use chat template like quote)
  metadata = engine.get_tokenizer()

  # Return the real tokenizer. Note that JetStream must be installed so
  # "_IS_STUB" must be False.
  tokenizer_model = engine.build_tokenizer(metadata)
  token_params_is_stub = getattr(_token_params_ns, "_IS_STUB", False)
  engine_api_is_stub = getattr(engine_api, "_IS_STUB", False)
  if is_decoupled() and (token_params_is_stub or engine_api_is_stub):
    raise RuntimeError(
        "JetStream disabled by DECOUPLE_GCLOUD=TRUE or stubbed; decode requires the JetStream tokenizer. "
        "Unset DECOUPLE_GCLOUD or install JetStream to run decode."
    )

  try:
    # TODO: update jetstream.engine.tokenizer_api.Tokenizer to maintain tokenizer state.
    has_chat_template = getattr(tokenizer_model.tokenizer, "chat_template", False)  # pytype: disable=attribute-error
  except AttributeError as _:
    has_chat_template = False
  # Converts input text to tokens:
  # is_bos: Whether to add a beginning of sequence token.
  # prefill_lengths: The length of the prompt, used to pad the rest of the array.
  # Returns:
  # tokens: The tokens of the prompt 1 x 64 array.
  # true_length: The actual length of the prompt. Engine use it to know where
  # the padding begins.
  tokens, true_length = tokenizer_model.encode(text, is_bos=not has_chat_template, prefill_lengths=[prefill_length])

  # Transformer processes all tokens in parallel. 
  # position_ids is used to calculate the position of each token so the order can
  # be restored.
  position_ids = None
  # Multimodal RoPE (Rotary Position Embedding) positional deltas.
  # It is always a 3-D tensor.
  # See MROPE.md
  mrope_position_deltas = None

  if config.use_multimodal:
    # Create placeholder tokens, often 256 tokens per image, to fill the token
    # positions reserved for images. Those placeholder tokens will be replaced
    # by the actual image tokens later.
    # It also add Bookends tokens for Gemma 3. e.g.
    # [\n, \n, <image_start>, ...256 placeholders..., <image_end>, \n, \n]
    tokens = mm_processor.prepare_text_for_image_fusion(tokens=tokens, config=config, processor_output=processor_outputs)
    true_length += image_offsets

    if config.use_mrope:
      from maxtext.multimodal import processor_qwen3_omni  # pylint: disable=import-outside-toplevel
      # position_ids: 3D position IDs. Shape: (3, batch, seq_len).
      # mrope_position_deltas: Position offset for each sequence. Shape: (batch, 1).
      position_ids, mrope_position_deltas = processor_qwen3_omni.get_rope_index(
          input_ids=tokens,
          image_grid_thw=processor_outputs.pixel_grid_thw,  # pytype: disable=attribute-error
          video_grid_thw=processor_outputs.video_grid_thw,  # pytype: disable=attribute-error
          attention_mask=np.ones_like(tokens),
          use_audio_in_video=config.use_audio and getattr(processor_outputs, 'num_videos', 0) > 0,
          audio_lengths=processor_outputs.audio_lengths,  # pytype: disable=attribute-error
          second_per_grids=processor_outputs.video_second_per_grid,  # pytype: disable=attribute-error
          spatial_merge_size=config.spatial_merge_size_for_vit,  # pytype: disable=attribute-error
          position_id_per_seconds=config.position_id_per_seconds,
      )

  assert (
      true_length <= config.max_prefill_predict_length
  ), f"Input token length {true_length} is longer than {config.max_prefill_predict_length=}"
  assert config.quantization != "fp8", "fp8 on NVIDIA GPUs is not supported in decode.py yet"
  assert config.quantization != "nanoo_fp8", "NANOO fp8 on AMD MI300/MI325 GPUs is not supported in decode.py yet"

  batch_size = int(config.per_device_batch_size * jax.device_count())
  assert (
      0 < _NUM_STREAMS <= batch_size
  ), f"The number of streams {_NUM_STREAMS} must be > 0 and <= batch size {batch_size}"

  prefill_result_list = []
  first_token_list = []
  sampled_tokens_list = []

  prof.activate(optional_postfix="trace")

  # Prefill
  rng, rng_prefill = jax.random.split(rng)  # Split RNG before calling prefill
  for i in range(_NUM_STREAMS):
    with jax.profiler.StepTraceAnnotation("prefill", stream=i):
      prefill_result, first_token = engine.prefill(
          params=params,
          padded_tokens=tokens,
          positions=position_ids,
          mrope_deltas=mrope_position_deltas,
          images=processor_outputs.pixel_values if config.use_multimodal else None,
          image_masks=processor_outputs.pixel_mask if config.use_multimodal and "llama4" in config.model_name else None,
          audio_values=processor_outputs.audio_values if config.use_audio else None,
          audio_masks=processor_outputs.audio_mask if config.use_audio else None,
          true_length=true_length,
          rng=rng_prefill,
          slot=i,
      )
    prefill_result_list.append(prefill_result)
    first_token_list.append(first_token)

  # Insert
  rng, rng_init_decode = jax.random.split(rng)
  # See INIT_DECODE_STATE.md
  decode_state = engine.init_decode_state(rng_init_decode)
  for i in range(_NUM_STREAMS):
    # Insert the prefill cache into the decode state.
    decode_state = engine.insert(prefill_result_list[i], decode_state, slot=i)

  # Generate
  prof_deactivated = False
  steps = range(config.max_prefill_predict_length, config.max_target_length)
  # first_token_list: list of 1st token results from prefill, 1 for each stream
  # _batch_first_result_token: batch the first token results (4) into batch
  # slots (8) and pad the empty slots with 0.
  # sampled_tokens_list: list of sampled (produced) tokens from decode.
  sampled_tokens_list.append(_batch_first_result_token(first_token_list, batch_size))
  for i in steps:
    rng, rng_generate = jax.random.split(rng)
    with jax.profiler.StepTraceAnnotation("generate", step=i):
      decode_state, sampled_tokens = engine.generate(params, decode_state, rng=rng_generate)

    # Automatically deactivate profiler after profiler_steps steps
    if i > config.max_prefill_predict_length + config.profiler_steps:
      prof.deactivate(blocking_object=sampled_tokens)
      prof_deactivated = True

    sampled_tokens_list.append(sampled_tokens)

  # Get results
  for i in range(_NUM_STREAMS):
    results = [t.get_result_at_slot(i).tokens.item() for t in sampled_tokens_list]
    output = tokenizer_model.decode(results)
    print(f"Input `{text}` -> `{output}`")

  assert output.startswith(
      config.autoregressive_decode_assert
  ), f"generated text mismatch {output=}, {config.autoregressive_decode_assert=}"

  # Deactivate profiler
  if not prof_deactivated:
    prof.deactivate(blocking_object=output)

  prof.post_process()


def _validate_config(config):
  assert config.load_full_state_path == "", (
      "Decode doesn't operate on full states! Convert to parameter checkpoint first."
      "Using generate_param_only_checkpoint."
  )


if __name__ == "__main__":
  app.run(main)
